apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloaksync
  labels:
    app.kubernetes.io/name: cloaksync
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloaksync
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloaksync
    spec:
      containers:
      - name: cloaksync
        image: troeger/cloaksync
        envFrom:
          - configMapRef:
              name: cloaksync
