apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: troeger/cloaksync
  newTag: v0.0.9

resources:
- ./../base

namespace: cloaksync

configMapGenerator:
- name: cloaksync
  envs:
    - .env
  behavior: create    
generatorOptions:
  disableNameSuffixHash: true 